version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "Pillow"
    open-pull-requests-limit: 15
    commit-message:
      prefix: "fix"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
